[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Olivier Chassé St-Laurent <oliviercsl@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2.0"
permutohedron = "0.2.4"
radixal = "0.3.0"
